name: playground
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  sidebarx: ^0.17.1
  flutter_colorpicker: ^1.1.0
  get: 4.6.6
  markdown_widget: ^2.3.2+6
  material_design_icons_flutter: ^7.0.7296
  url_launcher: ^6.3.0
  firebase_core: 3.1.1
  firebase_auth: 5.1.1
  image_picker: ^1.1.2
  flutter_zoom_drawer: ^3.2.0
  intl: ^0.19.0
  webview_flutter: 4.8.0
  flutter: 
    sdk: flutter
  cloud_firestore: ^5.0.2
  flutter_dotenv: ^5.1.0
  flutter_animate: ^4.5.0
  flutter_launcher_icons: ^0.13.1
  cached_network_image: ^3.3.1
  like_button: ^2.0.5
  loading_animation_widget: ^1.2.1
  firebase_messaging: ^15.0.2
  flutter_local_notifications: ^17.2.1
  quill_html_editor: ^2.2.8
  flutter_widget_from_html: ^0.15.1
  flutter_markdown: ^0.7.3
  flame: ^1.17.0
  flutter_joystick: ^0.2.0

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/dart.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/dart.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/dart.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/dart.png"

flutter: 
  assets: 
    - assets/
    - assets/icons/
    - assets/images/
    - assets/images/dino/
    - assets/.env
  uses-material-design: true

