name: playground
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  sidebarx: ^0.17.1
  flutter_colorpicker: ^1.1.0
  get: 4.6.6
  markdown_widget: ^2.3.2+6
  material_design_icons_flutter: ^7.0.7296
  url_launcher: ^6.3.0
  firebase_core: 3.1.1
  firebase_auth: 5.1.1
  image_picker: ^1.1.2
  flutter_zoom_drawer: ^3.2.0
  intl: ^0.19.0
  webview_flutter: 4.8.0
  flutter: 
    sdk: flutter
  cloud_firestore: ^5.0.2
  flutter_dotenv: ^5.1.0

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/.env
  uses-material-design: true

