name: playground
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  flutter_colorpicker: ^1.1.0
  flutter_markdown: ^0.7.2+1
  get: 4.6.6
  flutter: 
    sdk: flutter
  highlight: ^0.7.0
  syntax_highlight: ^0.4.0
dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

