// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMrXEfPsSYEmSje2BM68Kk5mXt97VR3Ps',
    appId: '1:914082894602:web:6fcd4c12cc3423a4fae0f3',
    messagingSenderId: '914082894602',
    projectId: 'playground-b0020',
    authDomain: 'playground-b0020.firebaseapp.com',
    storageBucket: 'playground-b0020.appspot.com',
    measurementId: 'G-9H2QWV6F9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmOsaA4AF_s7FGhmcUdnDTGHTqh38NK80',
    appId: '1:914082894602:android:a2c4fda376b17278fae0f3',
    messagingSenderId: '914082894602',
    projectId: 'playground-b0020',
    storageBucket: 'playground-b0020.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-gsp2mVpS7hlyHyRDIp0ongrwXyqVDVo',
    appId: '1:914082894602:ios:2cefe7a6fa1789ebfae0f3',
    messagingSenderId: '914082894602',
    projectId: 'playground-b0020',
    storageBucket: 'playground-b0020.appspot.com',
    iosClientId:
        '914082894602-5kchgjilnk86a17rhrvn1kokcidbuqfb.apps.googleusercontent.com',
    iosBundleId: 'com.example.playground',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-gsp2mVpS7hlyHyRDIp0ongrwXyqVDVo',
    appId: '1:914082894602:ios:2cefe7a6fa1789ebfae0f3',
    messagingSenderId: '914082894602',
    projectId: 'playground-b0020',
    storageBucket: 'playground-b0020.appspot.com',
    iosClientId:
        '914082894602-5kchgjilnk86a17rhrvn1kokcidbuqfb.apps.googleusercontent.com',
    iosBundleId: 'com.example.playground',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMrXEfPsSYEmSje2BM68Kk5mXt97VR3Ps',
    appId: '1:914082894602:web:dc299436d3e49d06fae0f3',
    messagingSenderId: '914082894602',
    projectId: 'playground-b0020',
    authDomain: 'playground-b0020.firebaseapp.com',
    storageBucket: 'playground-b0020.appspot.com',
    measurementId: 'G-M61NVEF5G8',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}
